service: ats-integration-service

provider:
  name: aws
  runtime: python3.10
  environment:
    ATS_BASE_URL: ${env:ATS_BASE_URL}
    ATS_API_KEY: ${env:ATS_API_KEY}
    ENV: ${env:ENV}

plugins:
  - serverless-offline

functions:
  getJobs:
    handler: src/handlers/jobs.handler
    events:
      - http:
          path: jobs
          method: get

  createCandidate:
    handler: src/handlers/candidates.handler
    events:
      - http:
          path: candidates
          method: post

  getApplications:
    handler: src/handlers/applications.handler
    events:
      - http:
          path: applications
          method: get
