service: ats-integration-service

provider:
  name: aws
  runtime: python3.10
  environment:
    ENV: ${env:ENV}
    ATS_PROVIDER: ${env:ATS_PROVIDER}

    ZOHO_CLIENT_ID: ${env:ZOHO_CLIENT_ID}
    ZOHO_CLIENT_SECRET: ${env:ZOHO_CLIENT_SECRET}
    ZOHO_REFRESH_TOKEN: ${env:ZOHO_REFRESH_TOKEN}
    ZOHO_API_BASE: ${env:ZOHO_API_BASE}

functions:
  getJobs:
    handler: src/handlers/jobs.handler
    events:
      - http:
          path: jobs
          method: get

  createCandidate:
    handler: src/handlers/candidates.handler
    events:
      - http:
          path: candidates
          method: post

  getApplications:
    handler: src/handlers/applications.handler
    events:
      - http:
          path: applications
          method: get

plugins:
  - serverless-offline
